### ISSUE TITLE
Determine which if any collections have incorrect eventDates

### ISSUE THREAD

**Issue by kyule** [BioKIC/NEON-Biorepository-Data-Docs#59]
There is a question about whether eventDate is correctly being populated in all collections. Concern has been raised that eventDate is actually shipment date or similar from the manifest in some collections. We need to determine if and where this is still occuring and determine how we will solve it until API is updated to consistently provide this information.

**Comment by arbolitoloco** [comment]
Wrote detailed documentation on what happens currently on our end when manifests are loaded and occurrences are harvested. Still need to work on info about Localities and Taxa, but done with Collection Dates. Document can be found at `Internal Workflows` > `Informatics` > `Occurrence Harvester`.

Basically it was hard to tell if the information was correct, because we are still relying on the Manifest to provide us with accurate dates. So Katie LeVan provided us with a full export of sample ids, named locations and event dates, and that was loaded in the database as a source of reliable information while the API development is ongoing. As of 2020/03/17, it seems like we have mostly clean, matching dates.
